// <auto-generated />
using Food_Menu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Food_Menu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407174106_FixImageUrls")]
    partial class FixImageUrls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Food_Menu.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg",
                            Name = "Pizza",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
                            Name = "Burger",
                            Price = 7.9900000000000002
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500",
                            Name = "Pasta",
                            Price = 11.99
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
                            Name = "Salad",
                            Price = 5.9900000000000002
                        });
                });

            modelBuilder.Entity("Food_Menu.Models.DishIngredient", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("DishIngredients");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            IngredientId = 1
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 4
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 7
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 1
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 3
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 6
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 5
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 8
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 4
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 1
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 5
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 3
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 7
                        });
                });

            modelBuilder.Entity("Food_Menu.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Onion"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mushrooms"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lettuce"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Beef"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Olives"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Garlic"
                        });
                });

            modelBuilder.Entity("Food_Menu.Models.DishIngredient", b =>
                {
                    b.HasOne("Food_Menu.Models.Dish", "Dish")
                        .WithMany("DishIngredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food_Menu.Models.Ingredient", "Ingredient")
                        .WithMany("DishIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Food_Menu.Models.Dish", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("Food_Menu.Models.Ingredient", b =>
                {
                    b.Navigation("DishIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
